{-# LANGUAGE ImportQualifiedPost #-}
{-# LANGUAGE RankNTypes #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE ViewPatterns #-}

module Mir.Intrinsics.Vector where

import Control.Monad.IO.Class (liftIO)

import Data.BitVector.Sized qualified as BV
import Data.Parameterized.NatRepr (knownNat)
import Data.Vector qualified as V

import Lang.Crucible.Backend (IsSymBackend, backendGetSym, addFailedAssertion)
import Lang.Crucible.CFG.Expr (App (VectorGetEntry, VectorSetEntry, VectorSize))
import Lang.Crucible.Simulator.RegValue (RegValue)
import Lang.Crucible.Simulator.SimError (SimErrorReason (..))
import Lang.Crucible.Types (NatType, TypeRepr, VectorType)

import What4.Interface (Pred, asBV, bvEq, bvLit, bvUlt, muxRange, asNat)

import Mir.FancyMuxTree (MonadAssert, MuxLeafT, leafAbort, leafAssert, subMuxLeafMA)
import Mir.Intrinsics.Size (UsizeType, natToUsize, usizeToNat)


vectorGetUsize :: (TypeRepr tp) ->
    (App ext f NatType -> f NatType) ->
    f (VectorType tp) -> f UsizeType -> App ext f tp
vectorGetUsize tpr wrap vec idx = VectorGetEntry tpr vec (wrap $ usizeToNat idx)

vectorSetUsize :: (TypeRepr tp) ->
    (App ext f NatType -> f NatType) ->
    f (VectorType tp) -> f UsizeType -> f tp -> App ext f (VectorType tp)
vectorSetUsize tpr wrap vec idx val = VectorSetEntry tpr vec (wrap $ usizeToNat idx) val

vectorSizeUsize ::
    (forall tp'. App ext f tp' -> f tp') ->
    f (VectorType tp) -> App ext f UsizeType
vectorSizeUsize wrap vec = natToUsize wrap $ wrap $ VectorSize vec


vectorTakeIO ::
    IsSymBackend sym bak =>
    bak ->
    TypeRepr tp ->
    V.Vector (RegValue sym tp) ->
    RegValue sym NatType ->
    IO (V.Vector (RegValue sym tp))
vectorTakeIO bak _tp v idx = case asNat idx of
    Just idx' -> return $ V.take (fromIntegral idx') v
    Nothing -> addFailedAssertion bak $
        GenericSimError "VectorTake index must be concrete"

vectorDropIO ::
    IsSymBackend sym bak =>
    bak ->
    TypeRepr tp ->
    V.Vector (RegValue sym tp) ->
    RegValue sym NatType ->
    IO (V.Vector (RegValue sym tp))
vectorDropIO bak _tpr v idx = case asNat idx of
    Just idx' -> return $ V.drop (fromIntegral idx') v
    Nothing -> addFailedAssertion bak $
        GenericSimError "VectorDrop index must be concrete"


leafIndexVectorWithSymIndex ::
    (MonadAssert sym bak m) =>
    bak ->
    (Pred sym -> a -> a -> IO a) ->
    V.Vector a ->
    RegValue sym UsizeType ->
    MuxLeafT sym m a
leafIndexVectorWithSymIndex bak iteFn v i
  | Just i' <- asBV i = case v V.!? fromIntegral (BV.asUnsigned i') of
        Just x -> return x
        Nothing -> leafAbort $ GenericSimError $
            "vector index out of range: the length is " ++ show (V.length v) ++
                " but the index is " ++ show i'
  -- Normally the final "else" branch returns the last element.  But the empty
  -- vector has no last element to return, so we have to special-case it.
  | V.null v = leafAbort $ GenericSimError $
        "vector index out of range: the length is " ++ show (V.length v)
  | otherwise = do
        let sym = backendGetSym bak
        inRange <- liftIO $ bvUlt sym i =<< bvLit sym knownNat (BV.mkBV knownNat (fromIntegral $ V.length v))
        leafAssert bak inRange $ GenericSimError $
            "vector index out of range: the length is " ++ show (V.length v)
        liftIO $ muxRange
            (\j -> bvEq sym i =<< bvLit sym knownNat (BV.mkBV knownNat (fromIntegral j)))
            iteFn
            (\j -> return $ v V.! fromIntegral j)
            0 (fromIntegral $ V.length v - 1)

leafAdjustVectorWithSymIndex ::
    forall sym bak a. (IsSymBackend sym bak) =>
    bak ->
    (Pred sym -> a -> a -> IO a) ->
    V.Vector a ->
    RegValue sym UsizeType ->
    (a -> MuxLeafT sym IO a) ->
    MuxLeafT sym IO (V.Vector a)
leafAdjustVectorWithSymIndex bak iteFn v i adj
  | Just (fromIntegral . BV.asUnsigned -> i') <- asBV i =
    if i' < V.length v then do
        x' <- adj $ v V.! i'
        return $ v V.// [(i', x')]
    else
        leafAbort $ GenericSimError $
            "vector index out of range: the length is " ++ show (V.length v) ++
                " but the index is " ++ show i'
  | otherwise = do
        inRange <- liftIO $ bvUlt sym i =<< bvLit sym knownNat (BV.mkBV knownNat (fromIntegral $ V.length v))
        leafAssert bak inRange $ GenericSimError $
            "vector index out of range: the length is " ++ show (V.length v)
        V.generateM (V.length v) go
  where
    sym = backendGetSym bak

    go :: Int -> MuxLeafT sym IO a
    go j = do
        hit <- liftIO $ bvEq sym i =<< bvLit sym knownNat (BV.mkBV knownNat (fromIntegral j))
        let x = v V.! j
        -- NB: With this design, any assert generated by `adj` will be
        -- replicated `N` times, in the form `assert (i == j -> p)`.  Currently
        -- this seems okay because the number of asserts will be linear, except
        -- in the case of nested arrays, which are uncommon.
        mx' <- subMuxLeafMA bak (adj x) hit
        case mx' of
            Just x' -> liftIO $ iteFn hit x' x
            Nothing -> return x
