# If you update this, make sure to also update RUST_TOOLCHAIN in
# .github/workflows/crux-mir-build.yml
ARG RUST_TOOLCHAIN="nightly-2025-09-14"
ARG CRUX_BUILD_DIR=/crux-mir/build

# Note that we intentionally do not use ubuntu:24.04 or later pending a
# resolution to https://github.com/coder/coder/issues/17316.
FROM ubuntu:22.04 AS build
ARG RUST_TOOLCHAIN
ARG CRUX_BUILD_DIR

RUN apt-get update && \
    apt-get install -y \
      # ghcup requirements
      build-essential curl libffi-dev libffi8 libgmp-dev libgmp10 libncurses-dev libncurses6 libtinfo6 \
      # Although ghcup's version of GHC shouldn't require libnuma, the aarch64 \
      # version does impose this requirement for unknown reasons. \
      # (See https://gitlab.haskell.org/ghc/ghc/-/issues/20876#note_399802) \
      libnuma1 \
      # Crux dependencies \
      pkg-config zlib1g-dev \
      # Miscellaneous
      unzip wget

RUN mkdir -p ${CRUX_BUILD_DIR}
ADD crucible ${CRUX_BUILD_DIR}/crucible
ADD crucible-concurrency ${CRUX_BUILD_DIR}/crucible-concurrency
ADD crucible-debug ${CRUX_BUILD_DIR}/crucible-debug
ADD crucible-mir ${CRUX_BUILD_DIR}/crucible-mir
ADD crucible-syntax ${CRUX_BUILD_DIR}/crucible-syntax
ADD crux ${CRUX_BUILD_DIR}/crux
ADD crux-mir ${CRUX_BUILD_DIR}/crux-mir
ADD dependencies ${CRUX_BUILD_DIR}/dependencies
ADD .github/cabal.project.crux-mir ${CRUX_BUILD_DIR}/cabal.project
ADD cabal.GHC-9.6.7.config ${CRUX_BUILD_DIR}/cabal.project.freeze

RUN useradd -m crux-mir && chown -R crux-mir:crux-mir /crux-mir
USER crux-mir
WORKDIR /crux-mir

ENV LANG=C.UTF-8 \
    LC_ALL=C.UTF-8 \
    PATH=/crux-mir/rootfs/usr/local/bin:/home/crux-mir/.cargo/bin:/home/crux-mir/.local/bin:/home/crux-mir/.ghcup/bin:$PATH

WORKDIR ${CRUX_BUILD_DIR}/dependencies/mir-json
RUN curl https://sh.rustup.rs -sSf | bash -s -- -y --profile minimal --default-toolchain ${RUST_TOOLCHAIN}
RUN rustup component add --toolchain ${RUST_TOOLCHAIN} rustc-dev rust-src
RUN cargo install --locked && \
    mir-json-translate-libs
# Define `CRUX_RUST_LIBRARY_PATH` this for the benefit of
# `cabal v2-test crux-mir` below.
ENV CRUX_RUST_LIBRARY_PATH=${CRUX_BUILD_DIR}/dependencies/mir-json/rlibs

RUN mkdir -p /crux-mir/rootfs/usr/local/bin
WORKDIR /crux-mir/rootfs/usr/local/bin
# The URL here is based on the same logic used to specify BUILD_TARGET_OS and
# BUILD_TARGET_ARCH in `.github/workflow/crux-mir-build.yml`, but specialized
# to Ubuntu.
ARG TARGETPLATFORM
RUN case ${TARGETPLATFORM} in \
      "linux/amd64") \
        WHAT4_SOLVERS_ARCH=X64 ;; \
      "linux/arm64" | "linux/arm64/v8") \
        WHAT4_SOLVERS_ARCH=ARM64 ;; \
      *) \
        printf "Unsupported architecture: %s\n" "${TARGETPLATFORM}" >&2 \
        exit 1 ;; \
    esac && \
    curl \
      --fail \
      --location \
      --proto '=https' \
      --show-error \
      --silent \
      --tlsv1.2 \
      --output solvers.zip \
      "https://github.com/GaloisInc/what4-solvers/releases/download/snapshot-20251112/ubuntu-22.04-${WHAT4_SOLVERS_ARCH}-bin.zip"
RUN unzip solvers.zip && rm solvers.zip && chmod +x *

WORKDIR /crux-mir
RUN case ${TARGETPLATFORM} in \
      "linux/amd64") \
        GHCUP_ARCH=x86_64 ;; \
      "linux/arm64" | "linux/arm64/v8") \
        GHCUP_ARCH=aarch64 ;; \
      *) \
        printf "Unsupported architecture: %s\n" "${TARGETPLATFORM}" >&2 \
        exit 1 ;; \
    esac && \
    mkdir -p /home/crux-mir/.local/bin && \
    curl \
      --fail \
      --location \
      --proto '=https' \
      --show-error \
      --silent \
      --tlsv1.2 \
      --output /home/crux-mir/.local/bin/ghcup \
      https://downloads.haskell.org/~ghcup/0.1.50.1/${GHCUP_ARCH}-linux-ghcup-0.1.50.1 && \
    chmod +x /home/crux-mir/.local/bin/ghcup
RUN mkdir -p /home/crux-mir/.ghcup && \
    ghcup --version && \
    ghcup install cabal 3.14.2.0 && \
    ghcup install ghc 9.6.7 && \
    ghcup set ghc 9.6.7

WORKDIR ${CRUX_BUILD_DIR}
RUN cabal update && \
    cabal build --only-dependencies crux-mir && \
    cabal build crux-mir && \
    cabal test crux-mir && \
    cp `cabal exec which crux-mir` /crux-mir/rootfs/usr/local/bin
USER root
RUN chown -R root:root /crux-mir/rootfs

FROM ubuntu:22.04
ARG CRUX_BUILD_DIR

RUN apt-get update && \
    apt-get install -y \
      libgmp10 zlib1g libcurl4 \
      # A C toolchain (needed to build crates that require a C compiler)
      clang

COPY --from=build /home/crux-mir/.cargo/bin /home/crux-mir/.cargo/bin
COPY --from=build /home/crux-mir/.rustup /home/crux-mir/.rustup
COPY --from=build /crux-mir/rootfs /
COPY --from=build ${CRUX_BUILD_DIR}/dependencies/mir-json/rlibs /crux-mir/rlibs

RUN useradd -m crux-mir && chown -R crux-mir:crux-mir /crux-mir /home/crux-mir
USER crux-mir
WORKDIR /

ENV LANG=C.UTF-8 \
    LC_ALL=C.UTF-8 \
    PATH=/home/crux-mir/.cargo/bin:$PATH \
    CRUX_RUST_LIBRARY_PATH=/crux-mir/rlibs

ENTRYPOINT ["/home/crux-mir/.cargo/bin/cargo", "crux-test"]
