# If you update this version number, make sure to update the value of
# LINUX_LLVM_VER in .github/ci.sh (in the install_llvm() function).
ARG LLVM_VER=14

FROM ubuntu:22.04 AS build
ARG LLVM_VER

RUN apt-get update && \
    apt-get install -y \
      # ghcup requirements
      build-essential curl libffi-dev libffi8 libgmp-dev libgmp10 libncurses-dev libncurses6 libtinfo6 \
      # Crux dependencies \
      pkg-config zlib1g-dev \
      # LLVM toolchain
      clang-${LLVM_VER} llvm-${LLVM_VER}-tools \
      # Miscellaneous
      unzip wget

ARG CRUX_BUILD_DIR=/crux-llvm/build
RUN mkdir -p ${CRUX_BUILD_DIR}
ADD crucible ${CRUX_BUILD_DIR}/crucible
ADD crucible-debug ${CRUX_BUILD_DIR}/crucible-debug
ADD crucible-llvm ${CRUX_BUILD_DIR}/crucible-llvm
ADD crucible-symio ${CRUX_BUILD_DIR}/crucible-symio
ADD crucible-syntax ${CRUX_BUILD_DIR}/crucible-syntax
ADD crux ${CRUX_BUILD_DIR}/crux
ADD crux-llvm ${CRUX_BUILD_DIR}/crux-llvm
ADD dependencies ${CRUX_BUILD_DIR}/dependencies
ADD .github/cabal.project.crux-llvm ${CRUX_BUILD_DIR}/cabal.project
ADD cabal.GHC-9.4.8.config ${CRUX_BUILD_DIR}/cabal.project.freeze
# Workaround until we have a more recent LLVM build available
RUN cp ${CRUX_BUILD_DIR}/crux-llvm/c-src/libcxx-7.1.0.bc ${CRUX_BUILD_DIR}/crux-llvm/c-src/libcxx-${LLVM_VER}.0.0.bc

RUN useradd -m crux-llvm && chown -R crux-llvm:crux-llvm /crux-llvm
USER crux-llvm
WORKDIR /crux-llvm

ENV CLANG=clang-${LLVM_VER} \
    LLVM_LINK=llvm-link-${LLVM_VER} \
    LANG=C.UTF-8 \
    LC_ALL=C.UTF-8

RUN mkdir -p rootfs/usr/local/bin
WORKDIR rootfs/usr/local/bin
# The URL here is based on the same logic used to specify BUILD_TARGET_OS and
# BUILD_TARGET_ARCH in `.github/workflow/crux-llvm-build.yml`, but specialized
# to x86-64 Ubuntu.
RUN curl -o solvers.zip -sL "https://github.com/GaloisInc/what4-solvers/releases/download/snapshot-20240212/ubuntu-22.04-X64-bin.zip"
RUN unzip solvers.zip && rm solvers.zip && chmod +x *

WORKDIR /crux-llvm
ENV PATH=/crux-llvm/rootfs/usr/local/bin:/home/crux-llvm/.local/bin:/home/crux-llvm/.ghcup/bin:$PATH
RUN mkdir -p /home/crux-llvm/.local/bin && \
    curl -L https://downloads.haskell.org/~ghcup/0.1.17.7/x86_64-linux-ghcup-0.1.17.7 -o /home/crux-llvm/.local/bin/ghcup && \
    chmod +x /home/crux-llvm/.local/bin/ghcup
RUN mkdir -p /home/crux-llvm/.ghcup && \
    ghcup --version && \
    ghcup install cabal 3.10.3.0 && \
    ghcup install ghc 9.4.8 && \
    ghcup set ghc 9.4.8

WORKDIR ${CRUX_BUILD_DIR}
RUN cabal v2-update && \
    cabal v2-build --only-dependencies crux-llvm && \
    cabal v2-build crux-llvm && \
    cabal v2-test crux-llvm && \
    cp `cabal v2-exec which crux-llvm` /crux-llvm/rootfs/usr/local/bin && \
    cp `cabal v2-exec which crux-llvm-svcomp` /crux-llvm/rootfs/usr/local/bin
USER root
RUN chown -R root:root /crux-llvm/rootfs

FROM ubuntu:22.04
ARG LLVM_VER

RUN apt-get update && \
    apt-get install -y \
      libgmp10 zlib1g clang-${LLVM_VER} llvm-${LLVM_VER}-tools unzip

COPY --from=build /crux-llvm/rootfs /
WORKDIR /crux-llvm
ADD crux-llvm/c-src c-src
RUN \
    # Use LLVM 7 bitcode file for libcxx until a more recent LLVM version is available
    cp c-src/libcxx-7.1.0.bc c-src/libcxx-${LLVM_VER}.0.0.bc && \
    # (Temporary) fix for
    # https://github.com/galoisinc/crucible/issues/887: the libDir default
    # is relative to the executable or failing that, the data dir as
    # reported by the build process, but neither matches WORKDIR/c-src.
    cp -r c-src /usr/local/

RUN useradd -m crux-llvm && chown -R crux-llvm:crux-llvm /crux-llvm /home/crux-llvm
USER crux-llvm
WORKDIR /

ENV LD_LIBRARY_PATH=/usr/local/lib \
    CLANG=clang-${LLVM_VER} \
    LLVM_LINK=llvm-link-${LLVM_VER} \
    LANG=C.UTF-8 \
    LC_ALL=C.UTF-8

ENTRYPOINT ["/usr/local/bin/crux-llvm"]
