# HLint's default suggestions are opinionated, so we disable all of them by
# default and enable just a small subset we can agree on.

- ignore: {}  # ignore all

- error:
    name: Use bvZero
    lhs: "What4.Interface.bvLit sym w (Data.BitVector.Sized.zero w)"
    rhs: 'What4.Interface.bvZero sym w'

- error:
    name: Use bvOne
    lhs: "What4.Interface.bvLit sym w (Data.BitVector.Sized.one w)"
    rhs: 'What4.Interface.bvOne sym w'
