flags: {}
packages:
  - crucible/
  - crucible-llvm/
  - crucible-server/

  - what4/
  - what4-abc/
  - what4-blt/
  - crucible-saw/

  - dependencies/abcBridge/
  - dependencies/aig/
  - dependencies/blt/
  - dependencies/cryptol/
  - dependencies/cryptol-verifier/
  - dependencies/hpb/
  - dependencies/llvm-pretty/
  - dependencies/parameterized-utils/
  - dependencies/saw-core/
  - dependencies/saw-core-aig/
  - dependencies/saw-core-sbv/
extra-deps:
  - GraphSCC-1.0.4
  - monadLib-3.7.3
  - simple-smt-0.7.1
  - sbv-7.7

resolver: lts-10.6
