flags: {}
packages:
  - crucible/
  - crucible-llvm/
  - crucible-abc/
  - crucible-blt/
  - crucible-saw/
  - crucible-server/
  - galois-matlab/
  - dependencies/abcBridge/
  - dependencies/aig/
  - dependencies/blt/
  - dependencies/cryptol/
  - dependencies/cryptol-verifier/
  - dependencies/hpb/
  - dependencies/llvm-pretty/
  - dependencies/parameterized-utils/
  - dependencies/saw-core/
  - dependencies/saw-core-aig/
  - dependencies/saw-core-sbv/
extra-deps:
  - GraphSCC-1.0.4
  - monadLib-3.7.3
  - simple-smt-0.7.1

resolver: lts-10.6
