flags: {}
extra-lib-dirs:
  - /usr/local/lib

packages:
- .
- ../crucible
- ../crucible-abc
- ../crucible-blt
- ../crucible-saw
- ../crucible-server
- ../galois-matlab
#- dependencies/golang
- ../../golang
- location:
    git: git@github.com:GaloisInc/abcBridge.git
    commit: 292194d9d073e78721b2f31ec43b3517c977c74e
  extra-dep: true
- location:
    git: git@github.com:GaloisInc/aig.git
    commit: 9f00c397a65dae5c37e031c0e8d815893dcbba27
  extra-dep: true
- location:
    git: git@github.com:GaloisInc/blt.git
    commit: 39b3ec7ee7cd88429d669b7960340cdaa9e5278f
  extra-dep: true
- location:
    git: git@github.com:GaloisInc/anastasia.git
    commit: 6087ab3f994497fabcb69b94c4563f1ac84b6699
  extra-dep: true
- location:
    git: git@github.com:GaloisInc/parameterized-utils.git
    commit: 7f9e6759a2b499f660ebe6777e3eff3afd05f1bb
  extra-dep: true
- location:
    git: git@github.com:GaloisInc/hpb.git
    commit: 09e927eaf39c62a235b74cb8bf7ef49f0b3233e3
  extra-dep: true
- location:
    git: git@github.com:GaloisInc/saw-core.git
    commit: 5fe4c445a022122bc024655243faefdfa966c19f
  extra-dep: true
- location:
    git: git@github.com:GaloisInc/llvm-pretty.git
    commit: 6b39ff89d7022a9d3e0733251527bc4fdc6c7382
  extra-dep: true
- location:
    git: git@github.com:GaloisInc/llvm-pretty-bc-parser.git
    commit: e718de8bea87a5f0f0dae3eb7cf8dfc31fab803d
  extra-dep: true
extra-deps:
- clock-0.7.2
- dotgen-0.4.2
- fgl-visualize-0.1.0.1
- alex-tools-0.1.1.0
resolver: lts-8.0
