module CrucibleProtobufTrace.ProtoDefs.MemoryState (module MemoryState) where

import Proto.CrucibleProtobufTrace.MemoryState as MemoryState
import Proto.CrucibleProtobufTrace.MemoryState_Fields as MemoryState