[package]
name = "crux-report-coverage"
version = "0.1.0"
authors = ["Stuart Pernsteiner <spernsteiner@galois.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1"
codespan-reporting = "0.9"
# `termcolor` version must match the dependency of `codespan-reporting`.
termcolor = "1"
