author:
  - Iavor Diatchki <iavor.diatchki@gmail.com>
  - Valentin Robert <valentin.robert.42@gmail.com>

dependencies:
  - ansi-wl-pprint
  - base ^>= 4.13
  - containers
  - crucible
  - crucible-llvm
  - crux
  - crux-llvm
  - extra
  - language-sally ^>= 0.2
  - lens
  - llvm-pretty
  - llvm-pretty-bc-parser
  - mtl
  - parameterized-utils
  - pretty
  - what4
  - what4-transition-system

executables:
  crucible-mc:
    main: Main.hs
    source-dirs: exe
    dependencies:
      - crucible-mc

ghc-options:
  - -Wall
  - -Werror=incomplete-patterns
  - -Werror=missing-methods
  - -Werror=overlapping-patterns

library:
  exposed-modules:
    - Lang.Crucible.ModelChecker.AsBaseType
    - Lang.Crucible.ModelChecker.CrucibleMC
    - Lang.Crucible.ModelChecker.Fresh
    - Lang.Crucible.ModelChecker.GlobalInfo
    - Lang.Crucible.ModelChecker.NamingConventions
    - Lang.Crucible.ModelChecker.SallyWhat4
    - Lang.Crucible.ModelChecker.SymbolicExecution.BlockInfo
    - Lang.Crucible.ModelChecker.SymbolicExecution.Debugging
    - Lang.Crucible.ModelChecker.SymbolicExecution.Driver
    - Lang.Crucible.ModelChecker.SymbolicExecution.PrettyPrinting
    - Lang.Crucible.ModelChecker.TransitionSystem.Builder
    - Lang.Crucible.ModelChecker.TransitionSystem.InitialState
    - Lang.Crucible.ModelChecker.TransitionSystem.Namespacer
    - Lang.Crucible.ModelChecker.TransitionSystem.Queries
    - Lang.Crucible.ModelChecker.TransitionSystem.StateCtx
    - Lang.Crucible.ModelChecker.TransitionSystem.Transitions
  source-dirs: src

license: BSD3

name: crucible-mc

version: 0.1.0.0
