#!/usr/bin/env bash

# Generate .travis.yml from the Dhall

cmd='cat travis.dhall | dhall-to-yaml --omitNull | sed "s/! //g" > ../.travis.yml'

if command -v nix-shell; then
  nix-shell -p dhall \
            -p dhall-json \
            --pure --run "$cmd"
  nix-shell -p 'with import (fetchTarball https://github.com/NixOS/nixpkgs-channels/archive/nixos-unstable.tar.gz) { }; travis' --pure --run "travis lint ../.travis.yml"
else
  $cmd
fi

echo "# This file was auto-generated by travis/gen.sh. DO NOT EDIT." >> ../.travis.yml
