# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: crucible_protobuf_trace/abort.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from crucible_protobuf_trace import common_pb2 as crucible__protobuf__trace_dot_common__pb2
from crucible_protobuf_trace import sym_expr_pb2 as crucible__protobuf__trace_dot_sym__expr__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#crucible_protobuf_trace/abort.proto\x1a$crucible_protobuf_trace/common.proto\x1a&crucible_protobuf_trace/sym_expr.proto\"\x1d\n\x0b\x41\x62ortedExec\x12\x0e\n\x06reason\x18\x01 \x01(\t\"6\n\x0b\x41\x62ortedExit\x12\x14\n\x0c\x65xit_success\x18\x01 \x01(\x08\x12\x11\n\texit_code\x18\x02 \x01(\x03\"\xc7\x01\n\rAbortedBranch\x12$\n\x0fsource_location\x18\x01 \x01(\x0b\x32\x0b.ProgramLoc\x12+\n\x12symbolic_condition\x18\x02 \x01(\x0b\x32\x0f.BoolExpression\x12\x30\n\x18\x61\x62ort_reason_true_branch\x18\x03 \x01(\x0b\x32\x0e.AbortedResult\x12\x31\n\x19\x61\x62ort_reason_false_branch\x18\x04 \x01(\x0b\x32\x0e.AbortedResult\"\x89\x01\n\rAbortedResult\x12$\n\x0c\x61\x62ort_single\x18\x01 \x01(\x0b\x32\x0c.AbortedExecH\x00\x12\"\n\nabort_exit\x18\x02 \x01(\x0b\x32\x0c.AbortedExitH\x00\x12&\n\x0c\x61\x62ort_branch\x18\x03 \x01(\x0b\x32\x0e.AbortedBranchH\x00\x42\x06\n\x04kindb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'crucible_protobuf_trace.abort_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ABORTEDEXEC._serialized_start=117
  _ABORTEDEXEC._serialized_end=146
  _ABORTEDEXIT._serialized_start=148
  _ABORTEDEXIT._serialized_end=202
  _ABORTEDBRANCH._serialized_start=205
  _ABORTEDBRANCH._serialized_end=404
  _ABORTEDRESULT._serialized_start=407
  _ABORTEDRESULT._serialized_end=544
# @@protoc_insertion_point(module_scope)
