name: crucible-go builds
on:
  push:
    branches: [master, "release-**"]
  pull_request:
  workflow_dispatch:

env:
  CI_TEST_LEVEL: "1"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04]
        cabal: ["3.10.3.0"]
        ghc: ["9.4.8", "9.6.5", "9.8.2"]
        include:
          - os: macos-14
            cabal: 3.10.3.0
            ghc: 9.8.2
          - os: windows-2019
            cabal: 3.10.3.0
            ghc: 9.8.2
    name: crucible-go - GHC v${{ matrix.ghc }} - ${{ matrix.os }}
    uses: GaloisInc/.github/.github/workflows/haskell-ci.yml@v1.4.2
    with:
      build-targets: pkg:crucible-go
      cabal: ${{ matrix.cabal }}
      # The numeric prefix can be updated to force the use of a new cache if
      # the current cache contents become corrupted/invalid.  This can
      # sometimes happen when (for example) the OS version is changed but
      # older .so files are cached, which can have various effects
      # (e.g. cabal complains it can't find a valid version of the "happy"
      # tool).
      #
      # This also periodically happens on MacOS builds due to a tar bug
      # (symptom: "No suitable image found ... unknown file type, first
      # eight bytes: 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00")
      cache-key-prefix: 1-go
      check: false
      ghc: ${{ matrix.ghc }}
      os: ${{ matrix.os }}
      pre-hook: |
        cp "cabal.GHC-${{ matrix.ghc }}.config" cabal.project.freeze

        env \
          SOLVER_PKG_VERSION="snapshot-20250326" \
          BUILD_TARGET_OS="${{ matrix.os }}" \
          BUILD_TARGET_ARCH="${RUNNER_ARCH}" \
          .github/ci.sh \
          install_solvers
      sdist-targets: crucible-go
      submodules: "true"
      test-targets: pkg:crucible-go
